apply shfmt

diff --git a/bin/validate_vcf b/bin/validate_vcf
--- a/bin/validate_vcf
+++ b/bin/validate_vcf
@@ -3,38 +3,42 @@
 set -euf -o pipefail
 
 while [ $# -gt 0 ]; do
-  case "$1" in
-    --input|-i)
-      if [[ $2 = -* ]]; then echo "Need argument for $1"; exit 1; fi
-      INPUT="$2"
-      shift
-      ;;
-    --output|-o)
-      if [[ $2 = -* ]]; then echo "Need argument for $1"; exit 1; fi
-      OUTPUT="$2"
-      shift
-      ;;
-    *)
-      echo "* Error: Invalid argument: $1"
-      exit 1
-  esac
-  shift
+    case "$1" in
+        --input | -i)
+            if [[ $2 = -* ]]; then
+                echo "Need argument for $1"
+                exit 1
+            fi
+            INPUT="$2"
+            shift
+            ;;
+        --output | -o)
+            if [[ $2 = -* ]]; then
+                echo "Need argument for $1"
+                exit 1
+            fi
+            OUTPUT="$2"
+            shift
+            ;;
+        *)
+            echo "* Error: Invalid argument: $1"
+            exit 1
+            ;;
+    esac
+    shift
 done
 
-
-if [ ! -f $INPUT ]
-then
+if [ ! -f $INPUT ]; then
     echo "Unable to open file $INPUT"
     exit 1
 fi
 
-if [ -v $OUTPUT ]
-then
+if [ -v $OUTPUT ]; then
     echo "No output specified"
     exit 2
 fi
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 # Run vcf-validator from vcftools
 vcf-validator $INPUT
