apply shellcheck

diff --git a/ops/package_data b/ops/package_data
--- a/ops/package_data
+++ b/ops/package_data
@@ -5,12 +5,12 @@ DATASETS=${DATASETS:-/anno/ops/datasets.json}
 PKG_NAMES=${PKG_NAMES:-}
 
 pushd /anno/data
-tmp_tarfile=$(mktemp -p "$PWD" --suffix=.tar)
+tmp_tarfile=$(mktemp -p "${PWD}" --suffix=.tar)
 
 rm_tmp() {
     EXIT_CODE=$?
-    if [ ! $EXIT_CODE -eq 0 ]; then
-        rm "$tmp_tarfile"
+    if [ ! ${EXIT_CODE} -eq 0 ]; then
+        rm "${tmp_tarfile}"
     fi
 }
 
@@ -26,52 +26,52 @@ update_tar() {
         # default: keep existing files
         tar_args[0]=-k
     fi
-    tar "${tar_args[@]}" -u -f "$tarfile" "$newfile"
+    tar "${tar_args[@]}" -u -f "${tarfile}" "${newfile}"
 }
 
 trap rm_tmp EXIT
 
 PKG_IN_ARCHIVE=$(mktemp)
 if [[ -f ${TAR_OUTPUT} ]]; then
-    cp "$TAR_OUTPUT" "$tmp_tarfile"
+    cp "${TAR_OUTPUT}" "${tmp_tarfile}"
     # Read out package names in archive (add them back at the end)
-    tar -xOf "$tmp_tarfile" PACKAGES >"$PKG_IN_ARCHIVE"
-    tar -f "$tmp_tarfile" --delete PACKAGES || true
+    tar -xOf "${tmp_tarfile}" PACKAGES >"${PKG_IN_ARCHIVE}"
+    tar -f "${tmp_tarfile}" --delete PACKAGES || true
 fi
 
 # update the tar to include sources.json
-update_tar "$tmp_tarfile" sources.json
+update_tar "${tmp_tarfile}" sources.json
 
-if [[ -z $PKG_NAMES ]]; then
+if [[ -z ${PKG_NAMES} ]]; then
     echo "No PKG_NAMES specified, tarring all datasets"
-    mapfile -t _PKG_NAMES_ARRAY < <(jq -r 'keys[]' "$DATASETS")
+    mapfile -t _PKG_NAMES_ARRAY < <(jq -r 'keys[]' "${DATASETS}")
 else
-    mapfile -t _PKG_NAMES_ARRAY < <(echo "$PKG_NAMES" | tr , $'\n')
+    mapfile -t _PKG_NAMES_ARRAY < <(echo "${PKG_NAMES}" | tr , $'\n')
 fi
 
 for PKG_NAME in "${_PKG_NAMES_ARRAY[@]}"; do
-    folder=$(jq -r ".$PKG_NAME.destination" "$DATASETS")
-    if [[ "$folder" == "null" ]]; then
-        echo "Unable to find package $PKG_NAME in $DATASETS. Continuing."
+    folder=$(jq -r ".${PKG_NAME}.destination" "${DATASETS}")
+    if [[ "${folder}" == "null" ]]; then
+        echo "Unable to find package ${PKG_NAME} in ${DATASETS}. Continuing."
         continue
     fi
 
-    echo "Adding $PKG_NAME to archive"
-    update_tar "$tmp_tarfile" "$folder"
-    echo "$PKG_NAME" >>"$PKG_IN_ARCHIVE"
+    echo "Adding ${PKG_NAME} to archive"
+    update_tar "${tmp_tarfile}" "${folder}"
+    echo "${PKG_NAME}" >>"${PKG_IN_ARCHIVE}"
 done
 
 COLOROFF='\033[0m'
 LIGHTGREEN='\033[1;32m'
 
 echo "Adding package list to archive and verifying data"
-sort "$PKG_IN_ARCHIVE" | uniq >PACKAGES
-update_tar "$tmp_tarfile" PACKAGES -W
+sort "${PKG_IN_ARCHIVE}" | uniq >PACKAGES
+update_tar "${tmp_tarfile}" PACKAGES -W
 echo "Packages in archive: "
-tar -xOf "$tmp_tarfile" PACKAGES
+tar -xOf "${tmp_tarfile}" PACKAGES
 
-echo -e "${LIGHTGREEN}\nVerifying temporary file\n\n$(tar -vdf "$tmp_tarfile")${COLOROFF}"
+echo -e "${LIGHTGREEN}\nVerifying temporary file\n\n$(tar -vdf "${tmp_tarfile}")${COLOROFF}"
 
 rm PACKAGES
-mv "$tmp_tarfile" "$TAR_OUTPUT"
-echo -e "\nCreated $TAR_OUTPUT"
+mv "${tmp_tarfile}" "${TAR_OUTPUT}"
+echo -e "\nCreated ${TAR_OUTPUT}"
diff --git a/ops/pg_sourceme b/ops/pg_sourceme
--- a/ops/pg_sourceme
+++ b/ops/pg_sourceme
@@ -1,12 +1,16 @@
 #!/bin/bash
 
+ts() {
+    date +%Y-%m-%d\ %H:%M:%S
+}
+
 if [[ "$(id -u -n)" == "root" ]]; then
     pg_user=postgres
 else
     pg_user=$(id -u)
 fi
 
-export PGDATA=${PGDATA:-"/pg_uta/$pg_user"}
+export PGDATA=${PGDATA:-"/pg_uta/${pg_user}"}
 export PGPORT=${PGPORT:-5432}
 
 export PG_BIN=/usr/lib/postgresql/13/bin
@@ -14,14 +18,14 @@ function pg_wait_for_ready() {
     timer=${1:-5}
     retries=${2:-10}
     N=0
-    while ! $PG_BIN/pg_isready --dbname=postgres --username=postgres --host localhost; do
-        echo "[$(date +%Y-%m-%d\ %H:%M:%S)] Postgres is unavailable - sleeping for $timer seconds"
+    while ! ${PG_BIN}/pg_isready --dbname=postgres --username=postgres --host localhost; do
+        echo "[$(ts)] Postgres is unavailable - sleeping for ${timer} seconds"
         N=$((N + 1))
-        if [[ $N -gt $retries ]]; then
-            echo >&2 "[$(date +%Y-%m-%d\ %H:%M:%S)] Postgres is unavailable - Reached maximum number of retries. Aborting."
+        if ((N > retries)); then
+            echo "[$(ts)] Postgres is unavailable - Reached maximum number of retries. Aborting." >&2
             exit 1
         fi
-        sleep "$timer"
+        sleep "${timer}"
     done
 }
 
@@ -29,19 +33,19 @@ function pg_shutdown() {
     echo "Shutting down PostgreSQL"
     # if pkill fails (no process found, etc), still exit the script
     if [[ "$(id -u -n)" == "root" ]]; then
-        gosu postgres "$PG_BIN/pg_ctl" stop -m s || exit $?
+        gosu postgres "${PG_BIN}/pg_ctl" stop -m s || exit $?
     else
-        "$PG_BIN/pg_ctl" stop -m s || exit $?
+        "${PG_BIN}/pg_ctl" stop -m s || exit $?
     fi
 }
 
 function pg_uta_sync_data() {
-    echo "Syncing Postgres UTA data from $ANNO_DATA/uta/ to $PGDATA"
-    mkdir -p "$PGDATA"
-    rsync -a --delete "$ANNO_DATA/uta/" "$PGDATA" --info=progress2 2>&1
+    echo "Syncing Postgres UTA data from ${ANNO_DATA}/uta/ to ${PGDATA}"
+    mkdir -p "${PGDATA}"
+    rsync -a --delete "${ANNO_DATA}/uta/" "${PGDATA}" --info=progress2 2>&1
 
     # Empty folders are not part of the DigitalOcean data, but postgres expects them. Therefore, create them here.
-    pushd "$PGDATA" || exit $?
+    pushd "${PGDATA}" || exit $?
     PG_FOLDERS=(
         base/pgsql_tmp
         pg_commit_ts
@@ -57,8 +61,8 @@ function pg_uta_sync_data() {
         pg_wal/archive_status
     )
     mkdir -p "${PG_FOLDERS[@]}"
-    chown -R "$pg_user" "$PGDATA"
-    chmod 0700 "$PGDATA"
+    chown -R "${pg_user}" "${PGDATA}"
+    chmod 0700 "${PGDATA}"
     popd || exit $?
 }
 
@@ -68,8 +72,8 @@ function pg_start() {
     trap pg_shutdown EXIT
     # if not running in singularity container, use gosu for postgres user
     if [[ "$(id -u -n)" == "root" ]]; then
-        exec gosu "$pg_user" "$PG_BIN/postgres" -c autovacuum=off
+        exec gosu "${pg_user}" "${PG_BIN}/postgres" -c autovacuum=off
     else
-        exec "$PG_BIN/postgres" -c autovacuum=off
+        exec "${PG_BIN}/postgres" -c autovacuum=off
     fi
 }
